name: 部署项目

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 设置 Node.js 环境
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 3. 安装依赖
      - name: 安装依赖
        run: |
          corepack enable || true
          npm ci --legacy-peer-deps

      # 4. 自动写入 homepage
      - name: 配置 homepage
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)    # 取仓库名
          USER_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1) # 取用户名
          npx json -I -f package.json -e "this.homepage='https://${USER_NAME}.github.io/${REPO_NAME}'"
          cat package.json | grep homepage

      # 5. 构建项目
      - name: 构建项目
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          npm run build
          > build/.nojekyll

      # 6. 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages   # 部署目标分支
          folder: build      # CRA 输出目录
          clean: true
